import "~/styles/globals.css";

// import Swiper styles
import "swiper/css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "iPhone LP Recreation",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/assets/images/ui/apple.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="fixed left-0 top-0 z-50 hidden bg-slate-500 p-2 text-lg text-white sm:bg-green-900 md:bg-green-600 lg:bg-blue xl:bg-red-900">
          <span className="sm:hidden">Base</span>
          <span className="hidden sm:inline md:hidden">SM</span>
          <span className="hidden md:inline lg:hidden">MD</span>
          <span className="hidden lg:inline xl:hidden">LG</span>
          <span className="hidden xl:inline 2xl:hidden">XL</span>
          <span className="hidden 2xl:inline">2XL</span>
        </div>
        {children}
      </body>
    </html>
  );
}
