import "~/styles/globals.css";

// import Swiper styles
import "swiper/css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Apple",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/images/apple.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
